import { Language } from '../types';

const translations: Record<Language, Record<string, string>> = {
  en: {
    nav_dashboard: 'Dashboard', nav_inventory: 'Inventory', nav_billing: 'Billing / POS', nav_ai: 'AI Assistant', nav_restock: 'Smart Restock', nav_invoice: 'Barcode & Invoice', nav_reviews: 'Reviews & Ratings',
    todaySales: 'Today\'s Sales', todayProfit: 'Today\'s Profit', totalProducts: 'Total Products', lowStock: 'Low Stock', bestSelling: 'Best Sellers', recentSales: 'Recent Sales', salesChart: 'Sales Last 7 Days', quickActions: 'Quick Actions', addProduct: 'Add Product', newSale: 'New Sale', askAI: 'Ask AI', viewRestock: 'View Restock', scanInvoice: 'Scan Barcode / Invoice', noRecentSales: 'No recent sales', sold: 'sold', noSalesData: 'No sales data available',
    inv_title: 'Inventory', inv_search: 'Search by name or category...', inv_add: 'Add Product', inv_product: 'Product', inv_category: 'Category', inv_stock: 'Stock', inv_purchase: 'Purchase Price', inv_selling: 'Selling Price', inv_profit: 'Profit/Unit', inv_margin: 'Margin %', inv_status: 'Status', inv_actions: 'Actions', inv_instock: 'In Stock', inv_lowstock: 'Low Stock', inv_edit: 'Edit', inv_delete: 'Delete', inv_addstock: 'Add Stock', inv_removestock: 'Remove Stock', inv_empty: 'No products found.', inv_confirmDelete: 'Are you sure you want to delete this product?', inv_name: 'Name', inv_minstock: 'Minimum Stock', inv_save: 'Save', inv_cancel: 'Cancel', inv_qty: 'Quantity',
    bill_title: 'Billing / POS', bill_search: 'Search products...', bill_cart: 'Cart', bill_empty: 'Cart is empty', bill_subtotal: 'Subtotal', bill_total: 'Total', bill_complete: 'Complete Sale', bill_newSale: 'New Sale', bill_print: 'Print Receipt', bill_receipt: 'Receipt', bill_thank: 'Thank you for shopping with us!', bill_invoice: 'Invoice', bill_date: 'Date',
    ai_title: 'AI Assistant', ai_placeholder: 'Ask me anything...', ai_send: 'Send', ai_listening: 'Listening...', ai_suggestions: 'Suggested queries:', ai_noVoice: 'Voice recognition not supported in this browser.', ai_confirm: 'Confirm', ai_cancel: 'Cancel', ai_thinking: 'Thinking...', ai_stockResponse: 'You have {count} units of {name} in stock.', ai_noProduct: 'Sorry, I couldn\'t find a product matching "{name}".', ai_lowStockList: 'The following items are low in stock:', ai_noLowStock: 'No products are currently low in stock. Great job!', ai_restockSuggestion: 'Here is what you should consider restocking based on current stock levels:', ai_todaySales: 'Your total sales today amount to ₹{amount}.', ai_todayProfit: 'Your profit today is ₹{amount}.', ai_noSalesToday: 'You haven\'t made any sales today yet.', ai_bestSellers: 'Your best-selling products are:', ai_noSalesData: 'Not enough sales data to determine best sellers.', ai_addConfirm: 'I will add {qty} to {name}. The stock will change from {current} to {new}. Should I proceed?', ai_removeConfirm: 'I will remove {qty} from {name}. The stock will change from {current} to {new}. Should I proceed?', ai_stockAdded: 'Successfully added {qty} units to {name}. New stock: {new}.', ai_stockRemoved: 'Successfully removed {qty} units from {name}. New stock: {new}.', ai_insufficientStock: 'Cannot remove {qty} from {name}. You only have {current} in stock.', ai_unknown: 'I am not sure how to help with that. Try asking about stock levels, sales, or restocking.', ai_greeting: 'Hello! I am your ShopStock AI Assistant. How can I help you today?',
    rst_title: 'Smart Restock', rst_product: 'Product', rst_stock: 'Current Stock', rst_avg: 'Avg Daily Sales', rst_days: 'Days Left', rst_rec: 'Recommend', rst_status: 'Status', rst_urgent: 'URGENT', rst_soon: 'SOON', rst_healthy: 'HEALTHY', rst_generate: 'Generate Restock List', rst_list: 'RESTOCK LIST', rst_copy: 'Copy to Clipboard', rst_copied: 'Copied!', rst_none: 'No items need restocking at the moment.', rst_estimated: 'Estimated recommendation based on past sales data.',
    inv_scanner_title: 'Invoice Scanner', inv_scanner_upload: 'Click or drag invoice image here', inv_scanner_preview: 'Preview', inv_scanner_demo: 'DEMO OCR MODE', inv_scanner_note: 'This is a simulation of OCR scanning.', inv_scanner_detected: 'Detected Items', inv_scanner_confirm: 'Confirm & Add to Inventory', inv_scanner_cancel: 'Cancel', inv_scanner_success: 'Successfully added scanned items to inventory!', inv_scanner_select: 'Select an image to scan', inv_scanner_edit: 'Qty to Add',
    confirm: 'Confirm', cancel: 'Cancel', save: 'Save', delete: 'Delete', edit: 'Edit', close: 'Close', reset: 'Reset Demo Data', resetConfirm: 'Are you sure you want to reset all demo data? This will erase any changes you made.',
    notif_title: 'Notifications', notif_empty: 'No notifications', notif_sale: 'Sale completed successfully', notif_stockAdded: 'Stock added: {qty} {name}', notif_stockRemoved: 'Stock removed: {qty} {name}', notif_lowstock: 'Low stock alert: {name}', notif_added: 'Product added: {name}', notif_updated: 'Product updated: {name}', notif_deleted: 'Product deleted: {name}', notif_invoice: 'Invoice scanned and items added'
  },
  te: {
    nav_dashboard: 'డాష్‌బోర్డ్', nav_inventory: 'ఇన్వెంటరీ', nav_billing: 'బిల్లింగ్', nav_ai: 'AI అసిస్టెంట్', nav_restock: 'స్మార్ట్ రీస్టాక్', nav_invoice: 'బార్‌కోడ్ & ఇన్‌వాయిస్', nav_reviews: 'సమీక్షలు & రేటింగ్‌లు',
    todaySales: 'నేటి అమ్మకాలు', todayProfit: 'నేటి లాభం', totalProducts: 'మొత్తం ఉత్పత్తులు', lowStock: 'తక్కువ స్టాక్', bestSelling: 'అత్యధికంగా అమ్ముడవుతున్నవి', recentSales: 'ఇటీవలి అమ్మకాలు', salesChart: 'గత 7 రోజుల అమ్మకాలు', quickActions: 'త్వరిత చర్యలు', addProduct: 'ఉత్పత్తిని జోడించండి', newSale: 'కొత్త అమ్మకం', askAI: 'AI ని అడగండి', viewRestock: 'రీస్టాక్ చూడండి', scanInvoice: 'బార్‌కోడ్ / ఇన్‌వాయిస్ స్కాన్', noRecentSales: 'ఇటీవలి అమ్మకాలు లేవు', sold: 'అమ్ముడయ్యాయి', noSalesData: 'అమ్మకాల డేటా లేదు',
    inv_title: 'ఇన్వెంటరీ', inv_search: 'పేరు లేదా వర్గం ద్వారా శోధించండి...', inv_add: 'ఉత్పత్తిని జోడించండి', inv_product: 'ఉత్పత్తి', inv_category: 'వర్గం', inv_stock: 'స్టాక్', inv_purchase: 'కొనుగోలు ధర', inv_selling: 'అమ్మకపు ధర', inv_profit: 'లాభం', inv_margin: 'మార్జిన్ %', inv_status: 'స్థితి', inv_actions: 'చర్యలు', inv_instock: 'స్టాక్ ఉంది', inv_lowstock: 'తక్కువ స్టాక్', inv_edit: 'సవరించు', inv_delete: 'తొలగించు', inv_addstock: 'స్టాక్ జోడించు', inv_removestock: 'స్టాక్ తీసివేయి', inv_empty: 'ఉత్పత్తులు కనుగొనబడలేదు.', inv_confirmDelete: 'మీరు ఖచ్చితంగా ఈ ఉత్పత్తిని తొలగించాలనుకుంటున్నారా?', inv_name: 'పేరు', inv_minstock: 'కనీస స్టాక్', inv_save: 'సేవ్ చేయి', inv_cancel: 'రద్దు చేయి', inv_qty: 'పరిమాణం',
    bill_title: 'బిల్లింగ్ / POS', bill_search: 'ఉత్పత్తులను శోధించండి...', bill_cart: 'కార్ట్', bill_empty: 'కార్ట్ ఖాళీగా ఉంది', bill_subtotal: 'ఉపమొత్తం', bill_total: 'మొత్తం', bill_complete: 'అమ్మకం పూర్తి చేయండి', bill_newSale: 'కొత్త అమ్మకం', bill_print: 'రసీదు ప్రింట్ చేయండి', bill_receipt: 'రసీదు', bill_thank: 'మా వద్ద కొనుగోలు చేసినందుకు ధన్యవాదాలు!', bill_invoice: 'ఇన్‌వాయిస్', bill_date: 'తేదీ',
    ai_title: 'AI అసిస్టెంట్', ai_placeholder: 'నన్ను ఏదైనా అడగండి...', ai_send: 'పంపు', ai_listening: 'వింటున్నాను...', ai_suggestions: 'సూచించిన ప్రశ్నలు:', ai_noVoice: 'ఈ బ్రౌజర్‌లో వాయిస్ గుర్తింపు మద్దతు లేదు.', ai_confirm: 'నిర్ధారించు', ai_cancel: 'రద్దు చేయి', ai_thinking: 'ఆలోచిస్తున్నాను...', ai_stockResponse: 'మీ వద్ద {name} కు సంబంధించి {count} యూనిట్లు స్టాక్ ఉంది.', ai_noProduct: 'క్షమించండి, "{name}" తో సరిపోలే ఉత్పత్తి కనుగొనబడలేదు.', ai_lowStockList: 'ఈ క్రింది వస్తువులు తక్కువ స్టాక్‌లో ఉన్నాయి:', ai_noLowStock: 'ప్రస్తుతం ఏ ఉత్పత్తులు తక్కువ స్టాక్‌లో లేవు. అద్భుతం!', ai_restockSuggestion: 'ప్రస్తుత స్టాక్ ఆధారంగా మీరు రీస్టాక్ చేయవలసినవి ఇక్కడ ఉన్నాయి:', ai_todaySales: 'ఈ రోజు మీ మొత్తం అమ్మకాలు ₹{amount}.', ai_todayProfit: 'ఈ రోజు మీ లాభం ₹{amount}.', ai_noSalesToday: 'మీరు ఈ రోజు ఇంకా ఎలాంటి అమ్మకాలు చేయలేదు.', ai_bestSellers: 'మీ అత్యధికంగా అమ్ముడవుతున్న ఉత్పత్తులు:', ai_noSalesData: 'బెస్ట్ సెల్లర్‌లను నిర్ణయించడానికి తగినంత అమ్మకాల డేటా లేదు.', ai_addConfirm: 'నేను {name} కు {qty} జోడిస్తాను. స్టాక్ {current} నుండి {new} కు మారుతుంది. నేను కొనసాగించవచ్చా?', ai_removeConfirm: 'నేను {name} నుండి {qty} తీసివేస్తాను. స్టాక్ {current} నుండి {new} కు మారుతుంది. నేను కొనసాగించవచ్చా?', ai_stockAdded: '{name} కు {qty} యూనిట్లు విజయవంతంగా జోడించబడ్డాయి. కొత్త స్టాక్: {new}.', ai_stockRemoved: '{name} నుండి {qty} యూనిట్లు విజయవంతంగా తీసివేయబడ్డాయి. కొత్త స్టాక్: {new}.', ai_insufficientStock: '{name} నుండి {qty} తీసివేయబడదు. మీ వద్ద కేవలం {current} స్టాక్ ఉంది.', ai_unknown: 'దానితో ఎలా సహాయం చేయాలో నాకు ఖచ్చితంగా తెలియదు. స్టాక్ స్థాయిలు, అమ్మకాలు లేదా రీస్టాకింగ్ గురించి అడగడానికి ప్రయత్నించండి.', ai_greeting: 'నమస్కారం! నేను మీ షాప్‌స్టాక్ AI అసిస్టెంట్‌ని. ఈరోజు నేను మీకు ఎలా సహాయం చేయగలను?',
    rst_title: 'స్మార్ట్ రీస్టాక్', rst_product: 'ఉత్పత్తి', rst_stock: 'ప్రస్తుత స్టాక్', rst_avg: 'సగటు రోజువారీ అమ్మకాలు', rst_days: 'మిగిలిన రోజులు', rst_rec: 'సూచన', rst_status: 'స్థితి', rst_urgent: 'అత్యవసరం', rst_soon: 'త్వరలో', rst_healthy: 'ఆరోగ్యకరం', rst_generate: 'రీస్టాక్ జాబితాను రూపొందించండి', rst_list: 'రీస్టాక్ జాబితా', rst_copy: 'క్లిప్‌బోర్డ్‌కు కాపీ చేయండి', rst_copied: 'కాపీ చేయబడింది!', rst_none: 'ప్రస్తుతం రీస్టాక్ చేయవలసిన వస్తువులు ఏవీ లేవు.', rst_estimated: 'గత అమ్మకాల డేటా ఆధారంగా అంచనా వేయబడిన సిఫార్సు.',
    inv_scanner_title: 'ఇన్‌వాయిస్ స్కానర్', inv_scanner_upload: 'ఇన్‌వాయిస్ చిత్రాన్ని ఇక్కడ క్లిక్ చేయండి లేదా లాగండి', inv_scanner_preview: 'ప్రివ్యూ', inv_scanner_demo: 'డెమో OCR మోడ్', inv_scanner_note: 'ఇది OCR స్కానింగ్ యొక్క అనుకరణ.', inv_scanner_detected: 'గుర్తించబడిన వస్తువులు', inv_scanner_confirm: 'నిర్ధారించండి & ఇన్వెంటరీకి జోడించండి', inv_scanner_cancel: 'రద్దు చేయి', inv_scanner_success: 'స్కాన్ చేసిన వస్తువులు ఇన్వెంటరీకి విజయవంతంగా జోడించబడ్డాయి!', inv_scanner_select: 'స్కాన్ చేయడానికి చిత్రాన్ని ఎంచుకోండి', inv_scanner_edit: 'జోడించవలసిన పరిమాణం',
    confirm: 'నిర్ధారించు', cancel: 'రద్దు చేయి', save: 'సేవ్ చేయి', delete: 'తొలగించు', edit: 'సవరించు', close: 'మూసివేయి', reset: 'డెమో డేటాను రీసెట్ చేయండి', resetConfirm: 'మీరు ఖచ్చితంగా డెమో డేటాను రీసెట్ చేయాలనుకుంటున్నారా?',
    notif_title: 'నోటిఫికేషన్‌లు', notif_empty: 'నోటిఫికేషన్‌లు లేవు', notif_sale: 'అమ్మకం విజయవంతంగా పూర్తయింది', notif_stockAdded: 'స్టాక్ జోడించబడింది: {qty} {name}', notif_stockRemoved: 'స్టాక్ తీసివేయబడింది: {qty} {name}', notif_lowstock: 'తక్కువ స్టాక్ హెచ్చరిక: {name}', notif_added: 'ఉత్పత్తి జోడించబడింది: {name}', notif_updated: 'ఉత్పత్తి నవీకరించబడింది: {name}', notif_deleted: 'ఉత్పత్తి తొలగించబడింది: {name}', notif_invoice: 'ఇన్‌వాయిస్ స్కాన్ చేయబడింది'
  },
  hi: {
    nav_dashboard: 'डैशबोर्ड', nav_inventory: 'इन्वेंटरी', nav_billing: 'बिलिंग / POS', nav_ai: 'AI असिस्टेंट', nav_restock: 'स्मार्ट रीस्टॉक', nav_invoice: 'बारकोड और चालान', nav_reviews: 'समीक्षाएं और रेटिंग',
    todaySales: 'आज की बिक्री', todayProfit: 'आज का लाभ', totalProducts: 'कुल उत्पाद', lowStock: 'कम स्टॉक', bestSelling: 'सबसे ज्यादा बिकने वाले', recentSales: 'हाल की बिक्री', salesChart: 'पिछले 7 दिनों की बिक्री', quickActions: 'त्वरित कार्रवाई', addProduct: 'उत्पाद जोड़ें', newSale: 'नई बिक्री', askAI: 'AI से पूछें', viewRestock: 'रीस्टॉक देखें', scanInvoice: 'बारकोड / चालान स्कैन', noRecentSales: 'कोई हाल की बिक्री नहीं', sold: 'बिका हुआ', noSalesData: 'कोई बिक्री डेटा उपलब्ध नहीं',
    inv_title: 'इन्वेंटरी', inv_search: 'नाम या श्रेणी से खोजें...', inv_add: 'उत्पाद जोड़ें', inv_product: 'उत्पाद', inv_category: 'श्रेणी', inv_stock: 'स्टॉक', inv_purchase: 'खरीद मूल्य', inv_selling: 'विक्रय मूल्य', inv_profit: 'लाभ/यूनिट', inv_margin: 'मार्जिन %', inv_status: 'स्थिति', inv_actions: 'कार्रवाई', inv_instock: 'स्टॉक में', inv_lowstock: 'कम स्टॉक', inv_edit: 'संपादित करें', inv_delete: 'हटाएं', inv_addstock: 'स्टॉक जोड़ें', inv_removestock: 'स्टॉक निकालें', inv_empty: 'कोई उत्पाद नहीं मिला।', inv_confirmDelete: 'क्या आप वाकई इस उत्पाद को हटाना चाहते हैं?', inv_name: 'नाम', inv_minstock: 'न्यूनतम स्टॉक', inv_save: 'सहेजें', inv_cancel: 'रद्द करें', inv_qty: 'मात्रा',
    bill_title: 'बिलिंग / POS', bill_search: 'उत्पाद खोजें...', bill_cart: 'कार्ट', bill_empty: 'कार्ट खाली है', bill_subtotal: 'उप-कुल', bill_total: 'कुल', bill_complete: 'बिक्री पूरी करें', bill_newSale: 'नई बिक्री', bill_print: 'रसीद प्रिंट करें', bill_receipt: 'रसीद', bill_thank: 'हमारे साथ खरीदारी करने के लिए धन्यवाद!', bill_invoice: 'चालान', bill_date: 'दिनांक',
    ai_title: 'AI असिस्टेंट', ai_placeholder: 'मुझसे कुछ भी पूछें...', ai_send: 'भेजें', ai_listening: 'सुन रहा हूँ...', ai_suggestions: 'सुझाए गए प्रश्न:', ai_noVoice: 'इस ब्राउज़र में वॉयस रिकग्निशन समर्थित नहीं है।', ai_confirm: 'पुष्टि करें', ai_cancel: 'रद्द करें', ai_thinking: 'सोच रहा हूँ...', ai_stockResponse: 'आपके पास स्टॉक में {name} की {count} इकाइयाँ हैं।', ai_noProduct: 'क्षमा करें, मुझे "{name}" से मेल खाने वाला कोई उत्पाद नहीं मिला।', ai_lowStockList: 'निम्नलिखित वस्तुओं का स्टॉक कम है:', ai_noLowStock: 'वर्तमान में किसी भी उत्पाद का स्टॉक कम नहीं है। बहुत बढ़िया!', ai_restockSuggestion: 'वर्तमान स्टॉक के आधार पर आपको निम्नलिखित वस्तुओं को रीस्टॉक करने पर विचार करना चाहिए:', ai_todaySales: 'आज आपकी कुल बिक्री ₹{amount} है।', ai_todayProfit: 'आज आपका लाभ ₹{amount} है।', ai_noSalesToday: 'आपने आज अभी तक कोई बिक्री नहीं की है।', ai_bestSellers: 'आपके सबसे ज्यादा बिकने वाले उत्पाद हैं:', ai_noSalesData: 'बेस्ट सेलर्स निर्धारित करने के लिए पर्याप्त बिक्री डेटा नहीं है।', ai_addConfirm: 'मैं {name} में {qty} जोड़ दूँगा। स्टॉक {current} से {new} हो जाएगा। क्या मुझे आगे बढ़ना चाहिए?', ai_removeConfirm: 'मैं {name} से {qty} निकाल दूँगा। स्टॉक {current} से {new} हो जाएगा। क्या मुझे आगे बढ़ना चाहिए?', ai_stockAdded: '{name} में {qty} इकाइयाँ सफलतापूर्वक जोड़ी गईं। नया स्टॉक: {new}।', ai_stockRemoved: '{name} से {qty} इकाइयाँ सफलतापूर्वक निकाली गईं। नया स्टॉक: {new}।', ai_insufficientStock: '{name} से {qty} नहीं निकाला जा सकता। आपके पास स्टॉक में केवल {current} है।', ai_unknown: 'मुझे यकीन नहीं है कि मैं इसमें कैसे मदद कर सकता हूँ। स्टॉक स्तर, बिक्री, या रीस्टॉकिंग के बारे में पूछने का प्रयास करें।', ai_greeting: 'नमस्ते! मैं आपका शॉपस्टॉक AI असिस्टेंट हूँ। आज मैं आपकी कैसे मदद कर सकता हूँ?',
    rst_title: 'स्मार्ट रीस्टॉक', rst_product: 'उत्पाद', rst_stock: 'वर्तमान स्टॉक', rst_avg: 'औसत दैनिक बिक्री', rst_days: 'बचे हुए दिन', rst_rec: 'सुझाव', rst_status: 'स्थिति', rst_urgent: 'अति आवश्यक', rst_soon: 'जल्द', rst_healthy: 'स्वस्थ', rst_generate: 'रीस्टॉक सूची जनरेट करें', rst_list: 'रीस्टॉक सूची', rst_copy: 'क्लिपबोर्ड पर कॉपी करें', rst_copied: 'कॉपी हो गया!', rst_none: 'फिलहाल किसी भी वस्तु को रीस्टॉक करने की आवश्यकता नहीं है।', rst_estimated: 'पिछले बिक्री डेटा के आधार पर अनुमानित सुझाव।',
    inv_scanner_title: 'चालान स्कैनर', inv_scanner_upload: 'चालान छवि यहाँ क्लिक करें या खींचें', inv_scanner_preview: 'पूर्वावलोकन', inv_scanner_demo: 'डेमो ओसीआर मोड', inv_scanner_note: 'यह ओसीआर स्कैनिंग का अनुकरण है।', inv_scanner_detected: 'पाई गई वस्तुएं', inv_scanner_confirm: 'पुष्टि करें और इन्वेंटरी में जोड़ें', inv_scanner_cancel: 'रद्द करें', inv_scanner_success: 'स्कैन की गई वस्तुओं को इन्वेंटरी में सफलतापूर्वक जोड़ा गया!', inv_scanner_select: 'स्कैन करने के लिए एक छवि चुनें', inv_scanner_edit: 'जोड़ने के लिए मात्रा',
    confirm: 'पुष्टि करें', cancel: 'रद्द करें', save: 'सहेजें', delete: 'हटाएं', edit: 'संपादित करें', close: 'बंद करें', reset: 'डेमो डेटा रीसेट करें', resetConfirm: 'क्या आप वाकई सभी डेमो डेटा रीसेट करना चाहते हैं?',
    notif_title: 'सूचनाएं', notif_empty: 'कोई सूचना नहीं', notif_sale: 'बिक्री सफलतापूर्वक पूरी हुई', notif_stockAdded: 'स्टॉक जोड़ा गया: {qty} {name}', notif_stockRemoved: 'स्टॉक निकाला गया: {qty} {name}', notif_lowstock: 'कम स्टॉक अलर्ट: {name}', notif_added: 'उत्पाद जोड़ा गया: {name}', notif_updated: 'उत्पाद अपडेट किया गया: {name}', notif_deleted: 'उत्पाद हटा दिया गया: {name}', notif_invoice: 'चालान स्कैन किया गया'
  },
  kn: {
    nav_dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', nav_inventory: 'ದಾಸ್ತಾನು', nav_billing: 'ಬಿಲ್ಲಿಂಗ್', nav_ai: 'AI ಸಹಾಯಕ', nav_restock: 'ಸ್ಮಾರ್ಟ್ ರಿಸ್ಟಾಕ್', nav_invoice: 'ಬಾರ್‌ಕೋಡ್ & ಇನ್ವಾಯ್ಸ್', nav_reviews: 'ವಿಮರ್ಶೆಗಳು ಮತ್ತು ರೇಟಿಂಗ್‌ಗಳು',
    todaySales: 'ಇಂದಿನ ಮಾರಾಟ', todayProfit: 'ಇಂದಿನ ಲಾಭ', totalProducts: 'ಒಟ್ಟು ಉತ್ಪನ್ನಗಳು', lowStock: 'ಕಡಿಮೆ ದಾಸ್ತಾನು', bestSelling: 'ಅತಿ ಹೆಚ್ಚು ಮಾರಾಟವಾಗುವ', recentSales: 'ಇತ್ತೀಚಿನ ಮಾರಾಟಗಳು', salesChart: 'ಕಳೆದ 7 ದಿನಗಳ ಮಾರಾಟ', quickActions: 'ತ್ವರಿತ ಕ್ರಿಯೆಗಳು', addProduct: 'ಉತ್ಪನ್ನವನ್ನು ಸೇರಿಸಿ', newSale: 'ಹೊಸ ಮಾರಾಟ', askAI: 'AI ಅನ್ನು ಕೇಳಿ', viewRestock: 'ರಿಸ್ಟಾಕ್ ವೀಕ್ಷಿಸಿ', scanInvoice: 'ಇನ್ವಾಯ್ಸ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ', noRecentSales: 'ಯಾವುದೇ ಇತ್ತೀಚಿನ ಮಾರಾಟಗಳಿಲ್ಲ', sold: 'ಮಾರಾಟವಾಗಿದೆ', noSalesData: 'ಯಾವುದೇ ಮಾರಾಟದ ಡೇಟಾ ಲಭ್ಯವಿಲ್ಲ',
    inv_title: 'ದಾಸ್ತಾನು', inv_search: 'ಹೆಸರು ಅಥವಾ ವರ್ಗದ ಮೂಲಕ ಹುಡುಕಿ...', inv_add: 'ಉತ್ಪನ್ನವನ್ನು ಸೇರಿಸಿ', inv_product: 'ಉತ್ಪನ್ನ', inv_category: 'ವರ್ಗ', inv_stock: 'ದಾಸ್ತಾನು', inv_purchase: 'ಖರೀದಿ ಬೆಲೆ', inv_selling: 'ಮಾರಾಟದ ಬೆಲೆ', inv_profit: 'ಲಾಭ/ಘಟಕ', inv_margin: 'ಮಾರ್ಜಿನ್ %', inv_status: 'ಸ್ಥಿತಿ', inv_actions: 'ಕ್ರಿಯೆಗಳು', inv_instock: 'ದಾಸ್ತಾನಿನಲ್ಲಿದೆ', inv_lowstock: 'ಕಡಿಮೆ ದಾಸ್ತಾನು', inv_edit: 'ತಿದ್ದು', inv_delete: 'ಅಳಿಸು', inv_addstock: 'ದಾಸ್ತಾನು ಸೇರಿಸಿ', inv_removestock: 'ದಾಸ್ತಾನು ತೆಗೆದುಹಾಕಿ', inv_empty: 'ಯಾವುದೇ ಉತ್ಪನ್ನಗಳು ಕಂಡುಬಂದಿಲ್ಲ.', inv_confirmDelete: 'ಈ ಉತ್ಪನ್ನವನ್ನು ಅಳಿಸಲು ನೀವು ಖಚಿತವಾಗಿ ಬಯಸುವಿರಾ?', inv_name: 'ಹೆಸರು', inv_minstock: 'ಕನಿಷ್ಠ ದಾಸ್ತಾನು', inv_save: 'ಉಳಿಸು', inv_cancel: 'ರದ್ದುಮಾಡು', inv_qty: 'ಪ್ರಮಾಣ',
    bill_title: 'ಬಿಲ್ಲಿಂಗ್ / POS', bill_search: 'ಉತ್ಪನ್ನಗಳನ್ನು ಹುಡುಕಿ...', bill_cart: 'ಕಾರ್ಟ್', bill_empty: 'ಕಾರ್ಟ್ ಖಾಲಿಯಾಗಿದೆ', bill_subtotal: 'ಉಪ-ಮೊತ್ತ', bill_total: 'ಒಟ್ಟು', bill_complete: 'ಮಾರಾಟವನ್ನು ಪೂರ್ಣಗೊಳಿಸಿ', bill_newSale: 'ಹೊಸ ಮಾರಾಟ', bill_print: 'ರಶೀದಿಯನ್ನು ಮುದ್ರಿಸಿ', bill_receipt: 'ರಶೀದಿ', bill_thank: 'ನಮ್ಮೊಂದಿಗೆ ಶಾಪಿಂಗ್ ಮಾಡಿದ್ದಕ್ಕಾಗಿ ಧನ್ಯವಾದಗಳು!', bill_invoice: 'ಇನ್ವಾಯ್ಸ್', bill_date: 'ದಿನಾಂಕ',
    ai_title: 'AI ಸಹಾಯಕ', ai_placeholder: 'ನನ್ನನ್ನು ಏನನ್ನಾದರೂ ಕೇಳಿ...', ai_send: 'ಕಳುಹಿಸು', ai_listening: 'ಆಲಿಸುತ್ತಿದೆ...', ai_suggestions: 'ಸೂಚಿಸಲಾದ ಪ್ರಶ್ನೆಗಳು:', ai_noVoice: 'ಈ ಬ್ರೌಸರ್‌ನಲ್ಲಿ ಧ್ವನಿ ಗುರುತಿಸುವಿಕೆ ಬೆಂಬಲಿತವಾಗಿಲ್ಲ.', ai_confirm: 'ಖಚಿತಪಡಿಸಿ', ai_cancel: 'ರದ್ದುಮಾಡು', ai_thinking: 'ಯೋಚಿಸುತ್ತಿದೆ...', ai_stockResponse: 'ನಿಮ್ಮ ಬಳಿ {count} ಘಟಕಗಳ {name} ದಾಸ್ತಾನಿನಲ್ಲಿದೆ.', ai_noProduct: 'ಕ್ಷಮಿಸಿ, "{name}" ಗೆ ಹೊಂದಿಕೆಯಾಗುವ ಯಾವುದೇ ಉತ್ಪನ್ನ ಕಂಡುಬಂದಿಲ್ಲ.', ai_lowStockList: 'ಕೆಳಗಿನ ವಸ್ತುಗಳು ಕಡಿಮೆ ದಾಸ್ತಾನಿನಲ್ಲಿವೆ:', ai_noLowStock: 'ಪ್ರಸ್ತುತ ಯಾವುದೇ ಉತ್ಪನ್ನಗಳು ಕಡಿಮೆ ದಾಸ್ತಾನಿನಲ್ಲಿಲ್ಲ. ಉತ್ತಮ ಕೆಲಸ!', ai_restockSuggestion: 'ಪ್ರಸ್ತುತ ದಾಸ್ತಾನಿನ ಆಧಾರದ ಮೇಲೆ ನೀವು ರಿಸ್ಟಾಕ್ ಮಾಡಲು ಪರಿಗಣಿಸಬೇಕಾದದ್ದು ಇಲ್ಲಿದೆ:', ai_todaySales: 'ಇಂದು ನಿಮ್ಮ ಒಟ್ಟು ಮಾರಾಟ ₹{amount}.', ai_todayProfit: 'ಇಂದು ನಿಮ್ಮ ಲಾಭ ₹{amount}.', ai_noSalesToday: 'ನೀವು ಇಂದು ಇನ್ನೂ ಯಾವುದೇ ಮಾರಾಟವನ್ನು ಮಾಡಿಲ್ಲ.', ai_bestSellers: 'ನಿಮ್ಮ ಹೆಚ್ಚು ಮಾರಾಟವಾಗುವ ಉತ್ಪನ್ನಗಳು:', ai_noSalesData: 'ಬೆಸ್ಟ್ ಸೆಲ್ಲರ್‌ಗಳನ್ನು ನಿರ್ಧರಿಸಲು ಸಾಕಷ್ಟು ಮಾರಾಟದ ಡೇಟಾ ಇಲ್ಲ.', ai_addConfirm: 'ನಾನು {name} ಗೆ {qty} ಸೇರಿಸುತ್ತೇನೆ. ದಾಸ್ತಾನು {current} ರಿಂದ {new} ಗೆ ಬದಲಾಗುತ್ತದೆ. ನಾನು ಮುಂದುವರಿಯಬಹುದೇ?', ai_removeConfirm: 'ನಾನು {name} ನಿಂದ {qty} ತೆಗೆದುಹಾಕುತ್ತೇನೆ. ದಾಸ್ತಾನು {current} ರಿಂದ {new} ಗೆ ಬದಲಾಗುತ್ತದೆ. ನಾನು ಮುಂದುವರಿಯಬಹುದೇ?', ai_stockAdded: '{name} ಗೆ {qty} ಘಟಕಗಳನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಸೇರಿಸಲಾಗಿದೆ. ಹೊಸ ದಾಸ್ತಾನು: {new}.', ai_stockRemoved: '{name} ನಿಂದ {qty} ಘಟಕಗಳನ್ನು ಯಶಸ್ವಿಯಾಗಿ ತೆಗೆದುಹಾಕಲಾಗಿದೆ. ಹೊಸ ದಾಸ್ತಾನು: {new}.', ai_insufficientStock: '{name} ನಿಂದ {qty} ತೆಗೆದುಹಾಕಲಾಗುವುದಿಲ್ಲ. ನಿಮ್ಮ ಬಳಿ ಕೇವಲ {current} ದಾಸ್ತಾನಿನಲ್ಲಿದೆ.', ai_unknown: 'ಇದರೊಂದಿಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಬೇಕೆಂದು ನನಗೆ ಖಚಿತವಿಲ್ಲ. ದಾಸ್ತಾನು ಮಟ್ಟಗಳು, ಮಾರಾಟಗಳು ಅಥವಾ ರಿಸ್ಟಾಕಿಂಗ್ ಬಗ್ಗೆ ಕೇಳಲು ಪ್ರಯತ್ನಿಸಿ.', ai_greeting: 'ನಮಸ್ಕಾರ! ನಾನು ನಿಮ್ಮ ಶಾಪ್‌ಸ್ಟಾಕ್ AI ಸಹಾಯಕ. ಇಂದು ನಾನು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?',
    rst_title: 'ಸ್ಮಾರ್ಟ್ ರಿಸ್ಟಾಕ್', rst_product: 'ಉತ್ಪನ್ನ', rst_stock: 'ಪ್ರಸ್ತುತ ದಾಸ್ತಾನು', rst_avg: 'ಸರಾಸರಿ ದೈನಂದಿನ ಮಾರಾಟ', rst_days: 'ಉಳಿದಿರುವ ದಿನಗಳು', rst_rec: 'ಶಿಫಾರಸು', rst_status: 'ಸ್ಥಿತಿ', rst_urgent: 'ತುರ್ತು', rst_soon: 'ಶೀಘ್ರದಲ್ಲೇ', rst_healthy: 'ಆರೋಗ್ಯಕರ', rst_generate: 'ರಿಸ್ಟಾಕ್ ಪಟ್ಟಿಯನ್ನು ರಚಿಸಿ', rst_list: 'ರಿಸ್ಟಾಕ್ ಪಟ್ಟಿ', rst_copy: 'ಕ್ಲಿಪ್‌ಬೋರ್ಡ್‌ಗೆ ನಕಲಿಸಿ', rst_copied: 'ನಕಲಿಸಲಾಗಿದೆ!', rst_none: 'ಪ್ರಸ್ತುತ ಯಾವುದೇ ವಸ್ತುಗಳನ್ನು ರಿಸ್ಟಾಕ್ ಮಾಡುವ ಅಗತ್ಯವಿಲ್ಲ.', rst_estimated: 'ಹಿಂದಿನ ಮಾರಾಟದ ಡೇಟಾದ ಆಧಾರದ ಮೇಲೆ ಅಂದಾಜು ಶಿಫಾರಸು.',
    inv_scanner_title: 'ಇನ್ವಾಯ್ಸ್ ಸ್ಕ್ಯಾನರ್', inv_scanner_upload: 'ಇನ್ವಾಯ್ಸ್ ಚಿತ್ರವನ್ನು ಇಲ್ಲಿ ಕ್ಲಿಕ್ ಮಾಡಿ ಅಥವಾ ಎಳೆಯಿರಿ', inv_scanner_preview: 'ಮುನ್ನೋಟ', inv_scanner_demo: 'ಡೆಮೊ OCR ಮೋಡ್', inv_scanner_note: 'ಇದು OCR ಸ್ಕ್ಯಾನಿಂಗ್‌ನ ಅನುಕರಣೆಯಾಗಿದೆ.', inv_scanner_detected: 'ಪತ್ತೆಯಾದ ವಸ್ತುಗಳು', inv_scanner_confirm: 'ಖಚಿತಪಡಿಸಿ ಮತ್ತು ದಾಸ್ತಾನಿಗೆ ಸೇರಿಸಿ', inv_scanner_cancel: 'ರದ್ದುಮಾಡು', inv_scanner_success: 'ಸ್ಕ್ಯಾನ್ ಮಾಡಿದ ವಸ್ತುಗಳನ್ನು ದಾಸ್ತಾನಿಗೆ ಯಶಸ್ವಿಯಾಗಿ ಸೇರಿಸಲಾಗಿದೆ!', inv_scanner_select: 'ಸ್ಕ್ಯಾನ್ ಮಾಡಲು ಚಿತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ', inv_scanner_edit: 'ಸೇರಿಸಲು ಪ್ರಮಾಣ',
    confirm: 'ಖಚಿತಪಡಿಸಿ', cancel: 'ರದ್ದುಮಾಡು', save: 'ಉಳಿಸು', delete: 'ಅಳಿಸು', edit: 'ತಿದ್ದು', close: 'ಮುಚ್ಚು', reset: 'ಡೆಮೊ ಡೇಟಾವನ್ನು ಮರುಹೊಂದಿಸಿ', resetConfirm: 'ನೀವು ಖಚಿತವಾಗಿ ಡೆಮೊ ಡೇಟಾವನ್ನು ಮರುಹೊಂದಿಸಲು ಬಯಸುವಿರಾ?',
    notif_title: 'ಅಧಿಸೂಚನೆಗಳು', notif_empty: 'ಯಾವುದೇ ಅಧಿಸೂಚನೆಗಳಿಲ್ಲ', notif_sale: 'ಮಾರಾಟ ಯಶಸ್ವಿಯಾಗಿ ಪೂರ್ಣಗೊಂಡಿದೆ', notif_stockAdded: 'ದಾಸ್ತಾನು ಸೇರಿಸಲಾಗಿದೆ: {qty} {name}', notif_stockRemoved: 'ದಾಸ್ತಾನು ತೆಗೆದುಹಾಕಲಾಗಿದೆ: {qty} {name}', notif_lowstock: 'ಕಡಿಮೆ ದಾಸ್ತಾನು ಎಚ್ಚರಿಕೆ: {name}', notif_added: 'ಉತ್ಪನ್ನವನ್ನು ಸೇರಿಸಲಾಗಿದೆ: {name}', notif_updated: 'ಉತ್ಪನ್ನವನ್ನು ನವೀಕರಿಸಲಾಗಿದೆ: {name}', notif_deleted: 'ಉತ್ಪನ್ನವನ್ನು ಅಳಿಸಲಾಗಿದೆ: {name}', notif_invoice: 'ಇನ್ವಾಯ್ಸ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಲಾಗಿದೆ'
  }
};

export function tr(lang: Language, key: string, vars?: Record<string, string | number>): string {
  let text = translations[lang]?.[key] || translations['en'][key] || key;
  if (vars) {
    Object.entries(vars).forEach(([k, v]) => {
      text = text.replace(new RegExp(`\\{${k}\\}`, 'g'), String(v));
    });
  }
  return text;
}
